#!/usr/bin/env ruby

require 'erb'
require 'date'

template = DATA.read
ARGV.each do |file|
  open(file) do |f|
    htmlfile = File.dirname(file) + '/' + File.basename(file, '.txt') + '.html'
    $html = `markdown #{file}`
    $html.gsub!(/\.txt/, '.html')
    $title = $1 if $html =~ /<h1>(.+?)<\/h1>/
    open(htmlfile, 'w') do |g|
      g.write(ERB.new(template).result)
    end
  end
end

__END__
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title><%= $title %></title>
    <style type="text/css">
body {
  margin: 1em;
}

h1, h2, h3 {
  margin-top: 1em;
}

pre {
  margin: 0.5em 2em;
  padding: 0.5em;
  background-color: #eee;
  border: 1px solid #ddd;
}
    </style>
  </head>
  <body>
    <%= $html %>

    <hr />
    <div style="text-align: right">
      <p>This page is generated by: txt2html.rb<br />
      Author: Tomohiro Matsuyama &lt;<a href="mailto: m2ym.pub@gmail.com">m2ym.pub@gmail.com</a>&gt;<br />
      Homepage: <a href="http://cx4a.org/">cx4a.org</a><br />
      Timestamp: <%= DateTime.now.asctime %></p>
    </div>
  </body>
</html
